In [3]:
import pandas as pd

In [7]:
df = pd.read_csv(r"zomato.csv", encoding="Latin1")

In [10]:
new = df[["Restaurant Name","City"]]

In [12]:
new.to_excel("myfile.xlsx")

In [16]:
df.columns
# 1. What is the highest 'Aggregate rating'
# 2. How many rests have the highest rating
df_highest = df[df["Aggregate rating"] == df["Aggregate rating"].max()]
df_highest_n = df_highest["Restaurant ID"].count()
df_highest_n

61

In [18]:
ratings = df["Aggregate rating"].value_counts()
ratings.loc[ratings.index.max()]

61

In [23]:
ratings.loc[ratings.index.min()]
# dir(ratings.index)

2148

In [25]:
df["Aggregate rating"].value_counts(True)

Aggregate rating
0.0    0.224898
3.2    0.054654
3.1    0.054340
3.4    0.052141
3.3    0.050571
3.5    0.050257
3.0    0.049000
3.6    0.047953
3.7    0.044707
3.8    0.041880
2.9    0.039891
3.9    0.035075
2.8    0.032981
4.1    0.028688
4.0    0.027850
2.7    0.026175
4.2    0.023139
2.6    0.019998
4.3    0.018218
4.4    0.015077
2.5    0.011517
4.5    0.009947
2.4    0.009109
4.6    0.008167
4.9    0.006387
2.3    0.004921
4.7    0.004397
2.2    0.002827
4.8    0.002618
2.1    0.001571
2.0    0.000733
1.9    0.000209
1.8    0.000105
Name: proportion, dtype: float64

In [28]:
ratings_gb = df.groupby("Aggregate rating")["Restaurant ID"].count()
ratings_gb.loc[ratings_gb.index.max()]

61

In [29]:
# How many unique cities are in the data set
ncities=df["City"].nunique()
ncities

141

In [32]:
# How many rests are in New Delhi
count = df[df['City'] == 'New Delhi'].count().iloc[0]
count

5473

In [33]:
cities = df["City"].value_counts()
cities.loc["New Delhi"]

5473

In [41]:
cities.to_frame()

                  count
City
New Delhi          5473
Gurgaon            1118
Noida              1080
Faridabad           251
Ghaziabad            25
...                 ...
Panchkula             1
Mc Millan             1
Mayfield              1
Macedon               1
Vineland Station      1

[141 rows x 1 columns]

In [36]:
cities_gb= df.groupby("City")[["Restaurant ID"]].count()
cities_gb.loc["New Delhi"]

Restaurant ID    5473
Name: New Delhi, dtype: int64

In [38]:
cities_gb.reset_index(inplace=True)

In [39]:
cities_gb.to_excel("ListRest.xlsx")

                City  Restaurant ID
0          Abu Dhabi             20
1               Agra             20
2          Ahmedabad             21
3             Albany             20
4          Allahabad             20
..               ...            ...
136          Weirton              1
137  Wellington City             20
138   Winchester Bay              1
139          Yorkton              1
140        ÛÁstanbul             14

[141 rows x 2 columns]

In [50]:
cn = df["Cuisines"].str.contains("Chinese").sum()

us = df["Cuisines"].str.contains("American").sum()

print(f"Chinese: {cn}", f"American: {us}")

Chinese: 2733 American: 405

In [57]:
# Get all Chinese rest in New Delhi
cond1 = df["Cuisines"].str.contains("Chinese",   case=False)
cond2 = df["City"]=="New Delhi"
cnl = df[cond1 & cond2][["Restaurant Name","City","Cuisines"]]

In [59]:
nd = df[df["City"]=="New Delhi"]
nd_chi = nd[ nd["Cuisines"].str.contains("Chinese", case=False)]
nd_chi

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
2564,582,Govardhan,1,New Delhi,"84, Adjacent Hero Motor Bike Showroom, Main Me...",Adchini,"Adchini, New Delhi",77.196924,28.535523,"South Indian, North Indian, Chinese",...,Indian Rupees(Rs.),No,Yes,No,No,2,3.4,Orange,Average,238
2569,948,Waves,1,New Delhi,"A-4, Sarvodaya Enclave, Adchini, New Delhi",Adchini,"Adchini, New Delhi",77.198808,28.538666,"North Indian, Chinese",...,Indian Rupees(Rs.),Yes,Yes,No,No,3,3.5,Yellow,Good,141
2570,2853,Delhi Darbar,1,New Delhi,"84, Main Road, Adchini, New Delhi",Adchini,"Adchini, New Delhi",77.196967,28.535763,"Chinese, North Indian",...,Indian Rupees(Rs.),No,No,No,No,2,2.2,Red,Poor,77
2577,308235,Sultanat,1,New Delhi,"31-BC, Ground Floor, Aditya Mega Mall, Karkard...","Aditya Mega Mall, Karkardooma","Aditya Mega Mall, Karkardooma, New Delhi",77.301603,28.656262,"North Indian, Chinese, Continental",...,Indian Rupees(Rs.),Yes,Yes,No,No,3,3.7,Yellow,Good,288
2579,307383,Clever Fox Cafe,1,New Delhi,"Red Fox Hotel, Asset 6, Aerocity Hospitality D...",Aerocity,"Aerocity, New Delhi",77.120642,28.551690,"North Indian, Continental, Chinese",...,Indian Rupees(Rs.),Yes,No,No,No,2,3.2,Orange,Average,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8001,18175274,Momos House,1,New Delhi,"G-130, Sudarshan Cinema Road, Yusuf Sarai, New...",Yusuf Sarai,"Yusuf Sarai, New Delhi",77.210156,28.561916,Chinese,...,Indian Rupees(Rs.),No,No,No,No,1,2.9,Orange,Average,5
8003,2605,Rhythm Restro-Bar,1,New Delhi,"50/8, 1st Floor, Main Market, Yusuf Sarai, New...",Yusuf Sarai,"Yusuf Sarai, New Delhi",77.207416,28.560355,"Mughlai, Chinese, North Indian",...,Indian Rupees(Rs.),Yes,No,No,No,3,3.0,Orange,Average,42
8009,954,Karnataka,1,New Delhi,"60/5, Yusuf Sarai Market, Yusuf Sarai, New Delhi",Yusuf Sarai,"Yusuf Sarai, New Delhi",77.207237,28.559442,"South Indian, North Indian, Chinese",...,Indian Rupees(Rs.),No,Yes,No,No,2,3.7,Yellow,Good,334
8020,18349925,Al-Kausar's,1,New Delhi,"K-65, Chinar Apartment, Jamia Nagar, Near Zaki...",Zakir Nagar,"Zakir Nagar, New Delhi",0.000000,0.000000,Chinese,...,Indian Rupees(Rs.),No,No,No,No,1,0.0,White,Not rated,0
8029,18168147,S.K. Fast Food,1,New Delhi,"161/32, Shop 3 Joga Bai, Main Road, Zakir Naga...",Zakir Nagar,"Zakir Nagar, New Delhi",77.283827,28.566189,Chinese,...,Indian Rupees(Rs.),No,No,No,No,1,0.0,White,Not rated,0

In [60]:
df.columns
# Based on 'Average Cost for two' find most expensive rests

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [61]:
cond_av= df["Average Cost for two"]==df["Average Cost for two"].max()
df[cond_av][[ 'Restaurant Name', 'Restaurant ID', 'Average Cost for two', 'Aggregate rating']]

,Restaurant Name,Restaurant ID,Average Cost for two,Aggregate rating
9283,Skye,7402935,800000,4.1
9284,Satoo - Hotel Shangri-La,7410290,800000,4.6

In [62]:
# Find most expensive chinese rstaturants in New Delhi
is_chinese = df["Cuisines"].str.contains("Chinese", case=False, na=False)
in_new_delhi = df["City"] == "New Delhi"
nd_ch = df[is_chinese & in_new_delhi]
nd_ch[nd_ch["Average Cost for two"] == nd_ch["Average Cost for two"].max()][["Restaurant Name", "Cuisines", "Average Cost for two"]]

,Restaurant Name,Cuisines,Average Cost for two
4088,Tian - Asian Cuisine Studio - ITC Maurya,"Asian, Japanese, Korean, Thai, Chinese",7000

In [63]:
nd = df[df["City"]=="New Delhi"]
nd_chi = nd[ nd["Cuisines"].str.contains("Chinese", case=False)]
r = nd_chi[nd_chi["Average Cost for two"] == nd_chi["Average Cost for two"].max()]
r[["Restaurant Name", "Cuisines", "Average Cost for two"]]

,Restaurant Name,Cuisines,Average Cost for two
4088,Tian - Asian Cuisine Studio - ITC Maurya,"Asian, Japanese, Korean, Thai, Chinese",7000

In [66]:
city = "New Delhi"
df.query("City == @city")
df.query("City == 'New Delhi' ")

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
2560,18287358,Food Cloud,1,New Delhi,"Aaya Nagar, New Delhi",Aaya Nagar,"Aaya Nagar, New Delhi",0.000000,0.000000,Cuisine Varies,...,Indian Rupees(Rs.),No,No,No,No,2,0.0,White,Not rated,2
2561,18216944,Burger.in,1,New Delhi,"84, Near Honda Showroom, Adchini, New Delhi",Adchini,"Adchini, New Delhi",77.196923,28.535382,Fast Food,...,Indian Rupees(Rs.),No,Yes,No,No,1,3.2,Orange,Average,46
2562,313333,Days of the Raj,1,New Delhi,"81/3, 1st Floor, Qutub Residency, Adchini, New...",Adchini,"Adchini, New Delhi",77.197475,28.535493,"North Indian, Seafood, Continental",...,Indian Rupees(Rs.),Yes,Yes,No,No,3,3.4,Orange,Average,45
2563,18384127,Dilli Ka Dhaba,1,New Delhi,"66 A, Ground Floor, Sri Aurobindo Marg, Adchin...",Adchini,"Adchini, New Delhi",77.198033,28.537547,"South Indian, North Indian",...,Indian Rupees(Rs.),No,No,No,No,2,2.6,Orange,Average,11
2564,582,Govardhan,1,New Delhi,"84, Adjacent Hero Motor Bike Showroom, Main Me...",Adchini,"Adchini, New Delhi",77.196924,28.535523,"South Indian, North Indian, Chinese",...,Indian Rupees(Rs.),No,Yes,No,No,2,3.4,Orange,Average,238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8028,18445274,Motu N Patlu,1,New Delhi,"Batla House Chowk, Near Jamia Milia Islamia, O...",Zakir Nagar,"Zakir Nagar, New Delhi",77.285065,28.566246,"Lebanese, North Indian, Fast Food",...,Indian Rupees(Rs.),No,No,No,No,1,0.0,White,Not rated,0
8029,18168147,S.K. Fast Food,1,New Delhi,"161/32, Shop 3 Joga Bai, Main Road, Zakir Naga...",Zakir Nagar,"Zakir Nagar, New Delhi",77.283827,28.566189,Chinese,...,Indian Rupees(Rs.),No,No,No,No,1,0.0,White,Not rated,0
8030,18429375,Sufiyan Restaurant,1,New Delhi,"57/12, Main Road, Zakir Nagar, New Delhi",Zakir Nagar,"Zakir Nagar, New Delhi",77.279779,28.567321,Mughlai,...,Indian Rupees(Rs.),No,No,No,No,1,0.0,White,Not rated,0
8031,310479,The Relax Point,1,New Delhi,"92/17, Zakir Nagar, New Delhi",Zakir Nagar,"Zakir Nagar, New Delhi",77.278543,28.566849,North Indian,...,Indian Rupees(Rs.),No,No,No,No,1,0.0,White,Not rated,1
8032,18212160,Zareen's Dastarkhwan,1,New Delhi,"Jamia Nagar, Zakir Nagar, New Delhi",Zakir Nagar,"Zakir Nagar, New Delhi",77.285696,28.565194,Awadhi,...,Indian Rupees(Rs.),No,No,No,No,2,0.0,White,Not rated,1

In [69]:
cities = ['Clatskanie', 'Cochrane', 'Columbus', 'Consort', 'Dalton',
       'Davenport', 'Des Moines']

In [74]:
df.query(" Cuisines in 'Chinese' and City in @cities ")

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
199,17330087,Chef Lee's Peking Restaurant,216,Columbus,"6100 Bradley Park Dr, Columbus, GA 31904",Columbus,"Columbus, Columbus",-84.960700,32.539300,Chinese,...,Dollar($),No,No,No,No,2,4.0,Green,Very Good,335
241,17334718,China Cafe,216,Davenport,"3018 E 53rd St, Davenport, IA 52807",Davenport,"Davenport, Davenport",-90.532100,41.574900,Chinese,...,Dollar($),No,No,No,No,2,4.0,Green,Very Good,112
263,17259166,Tsing Tsao South,216,Des Moines,"4230 Fleur Dr, Des Moines, IA 50321",Greater South Side,"Greater South Side, Des Moines",-93.645245,41.545869,Chinese,...,Dollar($),No,No,No,No,1,4.1,Green,Very Good,218

In [ ]:
df.query("Cuisines.str.contains('Chinese', na=False)", engine='python')